import ephem


avaliable_planet_list = ephem._libastro.builtin_planets()
planet_names = []
for i in avaliable_planet_list:
    planet_names.append(i[2])

constellation_dict = {
                'Andromeda': 'Andromeda - Андромеда',
                'Geminos': 'Geminos - Близнецы',
                'Twins': 'Twins - Близнецы',
                'Ursa Major': 'Ursa Major - Большая Медведица',
                'Big Dipper': 'Big Dipper - Большая Медведица',
                'Canis Major': 'Canis Major (The Great Dog) - Большой Пёс',
                'The Great Dog': 'Canis Major (The Great Dog) - Большой Пёс',
                'Great Dog': 'Canis Major (The Great Dog) - Большой Пёс',
                'Scopes': 'Scopes - Весы',
                'Aquarius': 'Aquarius - Водолей',
                'Auriga': 'Auriga - Возничий',
                'Wolf': 'Wolf - Волк',
                'Bootes': 'Bootes - Волопас',
                'Hair Of Veronica': 'Hair of Veronica - Волосы Вероники',
                'Raven': 'Raven - Ворон',
                'Hercules': 'Hercules - Геркулес',
                'Hydra': 'Hydra - Гидра',
                'Dove': 'Dove - Голубь',
                'Hounds Dogs': 'Hounds Dogs - Гончие Псы',
                'Virgo': 'Virgo - Дева',
                'Dolphin': 'Dolphin - Дельфин',
                'Dragon': 'Dragon - Дракон',
                'Unicorn': 'Unicorn - Единорог',
                'Altar': 'Altar - Жертвенник',
                'Painter': 'Painter - Живописец',
                'Giraffe': 'Giraffe - Жираф',
                'Crane': 'Crane - Журавль',
                'Hare': 'Hare - Заяц',
                'Ophiuchus': 'Ophiuchus - Змееносец',
                'Snake': 'Snake - Змея',
                'Cassiopeia': 'Cassiopeia - Кассиопея',
                'Centaur': 'Centaur - Кентавр',
                'Kiel': 'Kiel - Киль',
                'Whale': 'Whale - Кит',
                'Capricorn': 'Capricorn - Козерог',
                'Puppis': 'Puppis (Poop Deck) - Корма',
                'Poop Deck': 'Puppis (Poop Deck) - Корма',
                'Cygnus': 'Cygnus (The Swan) - Лебедь',
                'The Swan': 'Cygnus (The Swan) - Лебедь',
                'Swan': 'Cygnus (The Swan) - Лебедь',
                'Leo': 'Leo - Лев',
                'Lyra': 'Lyra - Лира',
                'Chanterelle': 'Chanterelle - Лисичка',
                'Ursa Minor': 'Ursa Minor (Small Dipper) - Малая Медведица',
                'Small Dipper': 'Ursa Minor (Small Dipper) - Малая Медведица',
                'Equuleus': 'Equuleus (Little Horse) - Малый Конь',
                'Little Horse': 'Equuleus (Little Horse) - Малый Конь',
                'Little Leo': 'Little Leo - Малый Лев',
                'Canis Minor': 'Canis Minor (The Lesser Dog) - Малый Пёс',
                'The Lesser Dog': 'Canis Minor (The Lesser Dog) - Малый Пёс',
                'Lesser Dog': 'Canis Minor (The Lesser Dog) - Малый Пёс',
                'Aries': 'Aries - Овен',
                'Octant': 'Octant - Октант',
                'Eagle': 'Eagle - Орёл',
                'Orion': 'Orion - Орион',
                'Peacock': 'Peacock - Павлин',
                'Sails': 'Sails - Паруса',
                'Pegasus': 'Pegasus - Пегас',
                'Perseus': 'Perseus - Персей',
                'Fornax': 'Fornax - Печь',
                'Cancer': 'Cancer - Рак',
                'Pisces': 'Pisces - Рыбы',
                'Lynx': 'Lynx - Рысь',
                'Northern Crown': 'Northern Crown - Северная Корона',
                'Scorpius': 'Scorpius - Скорпион',
                'Sagitta': 'Sagitta - Стрела',
                'Sagittarius': 'Sagittarius - Стрелец',
                'Taurus': 'Taurus - Телец',
                'Triangle': 'Triangle - Треугольник',
                'Phoenix': 'Phoenix - Феникс',
                'Cepheus': 'Cepheus - Цефей',
                'Bowl': 'Bowl - Чаша',
                'Eridanus': 'Eridanus - Эридан',
                'South Hydra': 'South Hydra - Южная Гидра',
                'Southern Crown': 'Southern Crown - Южная Корона',
                'Southern Fish': 'Southern Fish - Южная Рыба',
                'Crux': 'Crux - Южный Крест',
                'Southern Triangle': 'Southern Triangle - Южный Треугольник',
                'Lizard': 'Lizard - Ящерица',
                'Unicorn': 'Unicorn - Единорог'
}